### PR TITLE
Prevent duplicate styles

### PR DESCRIPTION
**Pull request by gkiely**
-Prevent parsing of files that have been defined by the user
-Added tests on regex101
-Added ds_store to gitignore

### CODE REVIEW

**Comment by gkiely** [comment]
Hi @mathisonian I've cleaned this up a bit since the last pr, let me know if you have any questions, happy to add more tests etc.

-Grant

**Comment by mathisonian** [comment]
Thanks for submitting this @gkiely! everything looks good to me, i'll update on npm as well

**Comment by mathisonian** [comment]
this is released in `v0.3.3` on npm, and I've also bumped the entire project version to `v1.0.0` so we can start following semver

**Comment by gkiely** [comment]
Nice work @mathisonian!

**Pull request merged**
